# https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# https://github.com/marketplace/actions/gradle-command
name: Check build and run tests
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '**.md'
      - '**.adoc'
  push:
    branches:
      - develop
      - master
    paths-ignore:
      - '**.md'
      - '**.adoc'
jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup SDK
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Gradle test
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: --scan test
