# https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# https://github.com/marketplace/actions/gradle-command
name: Check build and run tests
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '.editorconfig'
      - '**/.gitignore'
  push:
    branches:
      - develop
      - master
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '.editorconfig'
      - '**/.gitignore'
jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1.1.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: test allTests --stacktrace --scan -PbuildScan.termsOfServiceAgree=yes
