# https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# https://github.com/marketplace/actions/gradle-command
name: Publish to repository
on:
  workflow_dispatch:
    inputs:
      dummy:
        description: 'Dummy value'
        required: false
        default: ''
  push:
    paths:
      - 'libraries_version.properties'
    branches:
      - master
      - develop
jobs:
  windows-publishing:
    strategy:
      matrix:
        qualifier: [MingwX64, MingwX86]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
      - name: Run gradle task with retries
        run: ./run_gradle_task_with_retries.sh publish${{ matrix.qualifier }}PublicationToBintrayRepository -Pbintray_user=${{ secrets.bintray_user }} -Pbintray_api_key=${{ secrets.bintray_api_key }}
  linux-publishing:
    strategy:
      matrix:
        arch: [X64, Arm32Hfp, Arm64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
      - name: Run gradle task with retries
        run: ./run_gradle_task_with_retries.sh publishLinux${{ matrix.arch }}PublicationToBintrayRepository -Pbintray_user=${{ secrets.bintray_user }} -Pbintray_api_key=${{ secrets.bintray_api_key }}
  mac-publishing:
    strategy:
      matrix:
        qualifier: [MacosX64, IosArm32, IosArm64, IosX64, WatchosArm32, WatchosArm64, WatchosX86, TvosArm64, TvosX64]
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
      - name: Run gradle task with retries
        run: ./run_gradle_task_with_retries.sh publish${{ matrix.qualifier }}PublicationToBintrayRepository -Pbintray_user=${{ secrets.bintray_user }} -Pbintray_api_key=${{ secrets.bintray_api_key }}
  host-independent-platforms-publishing:
    strategy:
      matrix:
        qualifier: [Android, Jvm, Js]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
      - name: Run gradle task with retries
        run: ./run_gradle_task_with_retries.sh publish${{ matrix.qualifier }}PublicationToBintrayRepository -Pbintray_user=${{ secrets.bintray_user }} -Pbintray_api_key=${{ secrets.bintray_api_key }}
  multiplatform-metadata-publishing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
      - name: Run gradle task with retries
        run: ./run_gradle_task_with_retries.sh publishMetadataPublicationToBintrayRepository publishKotlinMultiplatformPublicationToBintrayRepository -Pbintray_user=${{ secrets.bintray_user }} -Pbintray_api_key=${{ secrets.bintray_api_key }}
