# https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# https://github.com/marketplace/actions/gradle-command
name: On release
on:
    push:
        branches:
            - master
            - develop
    release:
        # Only use the types keyword to narrow down the activity types that will trigger your workflow.
        types: [published, created, edited]
jobs:
    gradle:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-java@v1
              with:
                  java-version: 11
            - uses: eskatos/gradle-command-action@v1
              with:
                  gradle-version: 5.6.3
                  arguments: --scan --dry-run publishToRepository
