# https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
name: Publish to repository
on:
  push:
    paths:
      - 'libraries_version.properties'
    branches:
      - master
      - develop
jobs:
  windows-publishing:
    runs-on: windows-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Publish Windows artifacts
        run: ./gradlew publishMingwX64PublicationToBintrayRepository publishMingwX86PublicationToBintrayRepository
  linux-publishing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Publish Linux artifacts
        run: ./gradlew publishLinuxX64PublicationToBintrayRepository publishLinuxArm64PublicationToBintrayRepository publishLinuxArm32HfpPublicationToBintrayRepository
  macos-publishing:
    runs-on: macOS-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Publish all artifacts macOS can publish
        run: ./gradlew publishAllPublicationsToBintrayRepository
env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=true -Dkotlin.incremental=false -Dorg.gradle.project.kotlin.incremental.multiplatform=false -Dorg.gradle.project.kotlin.native.disableCompilerDaemon=true -Dorg.gradle.project.buildScan.termsOfServiceAgree=yes -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
  ORG_GRADLE_PROJECT_bintray_user: ${{ secrets.BINTRAY_USER }}
  ORG_GRADLE_PROJECT_bintray_api_key: ${{ secrets.BINTRAY_API_KEY }}
