# https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# https://github.com/marketplace/actions/gradle-command
name: Publish to repository
on:
  push:
    paths:
      - 'libraries_version.properties'
    branches:
      - master
      - develop
jobs:
  mac-and-windows-publishing:
    strategy:
      matrix:
        os: [macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup SDK
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Gradle test
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: -Pbintray_user=${{ secrets.bintray_user }} -Pbintray_api_key=${{ secrets.bintray_api_key }} --scan publishToRepository
  linux-and-mpp-publishing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup SDK
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Gradle test
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: -Pbintray_user=${{ secrets.bintray_user }} -Pbintray_api_key=${{ secrets.bintray_api_key }} --scan -Pmpp.publishAll=true publishToRepository
