# https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# https://github.com/marketplace/actions/gradle-command
name: Publish to repository
on:
  push:
    paths:
      - 'libraries_version.properties'
    branches:
      - master
      - develop
jobs:
  windows-publishing:
    strategy:
      matrix:
        qualifier: [MingwX64, MingwX86]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1.1.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle
          restore-keys: ${{ runner.os }}-gradle
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: publish${{ matrix.qualifier }}PublicationToBintrayRepository -Pbintray_user=${{ secrets.bintray_user }} -Pbintray_api_key=${{ secrets.bintray_api_key }} --scan -PbuildScan.termsOfServiceAgree=yes
  linux-publishing:
    strategy:
      matrix:
        arch: [X64, Arm32Hfp, Arm64]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1.1.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle
          restore-keys: ${{ runner.os }}-gradle
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: publishLinux${{ matrix.arch }}PublicationToBintrayRepository -Pbintray_user=${{ secrets.bintray_user }} -Pbintray_api_key=${{ secrets.bintray_api_key }} --scan -PbuildScan.termsOfServiceAgree=yes
  mac-publishing:
    strategy:
      matrix:
        qualifier: [MacosX64, IosArm32, IosArm64, IosX64, WatchosArm32, WatchosArm64, WatchosX86, TvosArm64, TvosX64]
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1.1.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle
          restore-keys: ${{ runner.os }}-gradle
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: publish${{ matrix.qualifier }}PublicationToBintrayRepository -Pbintray_user=${{ secrets.bintray_user }} -Pbintray_api_key=${{ secrets.bintray_api_key }} --scan -PbuildScan.termsOfServiceAgree=yes
  mpp-publishing:
    strategy:
      matrix:
        qualifier: [Android, Jvm, Js, Metadata, KotlinMultiplatform]
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1.1.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle
          restore-keys: ${{ runner.os }}-gradle
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: publish${{ matrix.qualifier }}PublicationToBintrayRepository -Pbintray_user=${{ secrets.bintray_user }} -Pbintray_api_key=${{ secrets.bintray_api_key }} --scan -PbuildScan.termsOfServiceAgree=yes
